"""Versioned, dependency-free local ASR adapter boundary."""

from .adapter import (
    ASR_CONTRACT_VERSION,
    AdapterConfig,
    AsrBackend,
    AsrBackendError,
    AsrStageError,
    AudioChunk,
    BackendResult,
    ChunkCheckpoint,
    ChunkPlanner,
    DeterministicFixtureBackend,
    Failure,
    HallucinationPolicy,
    LocalAsrAdapter,
    map_sample_interval,
    Provenance,
    RawUtterance,
    RawWord,
    TimeBase,
    TimeInterval,
    TimePoint,
    Transcript,
    VadSegment,
    parse_transcript_json,
    validate_transcript,
)

__all__ = [
    "ASR_CONTRACT_VERSION",
    "AdapterConfig",
    "AsrBackend",
    "AsrBackendError",
    "AsrStageError",
    "AudioChunk",
    "BackendResult",
    "ChunkCheckpoint",
    "ChunkPlanner",
    "DeterministicFixtureBackend",
    "Failure",
    "HallucinationPolicy",
    "LocalAsrAdapter",
    "map_sample_interval",
    "Provenance",
    "RawUtterance",
    "RawWord",
    "TimeBase",
    "TimeInterval",
    "TimePoint",
    "Transcript",
    "VadSegment",
    "parse_transcript_json",
    "validate_transcript",
]
